INSERT INTO dbo.countries VALUES ('Bonaire, Saint Eustatius and Saba', 'BQ');
INSERT INTO dbo.countries VALUES ('Aruba', 'AW');
INSERT INTO dbo.countries VALUES ('Antigua and Barbuda', 'AG');
INSERT INTO dbo.countries VALUES ('United Arab Emirates', 'AE');
INSERT INTO dbo.countries VALUES ('Afghanistan', 'AF');
INSERT INTO dbo.countries VALUES ('Algeria', 'DZ');
INSERT INTO dbo.countries VALUES ('Azerbaijan', 'AZ');
INSERT INTO dbo.countries VALUES ('Albania', 'AL');
INSERT INTO dbo.countries VALUES ('Armenia', 'AM');
INSERT INTO dbo.countries VALUES ('Angola', 'AO');
INSERT INTO dbo.countries VALUES ('American Samoa', 'AS');
INSERT INTO dbo.countries VALUES ('Argentina', 'AR');
INSERT INTO dbo.countries VALUES ('Australia', 'AU');
INSERT INTO dbo.countries VALUES ('Ashmore and Cartier Islands', '\N');
INSERT INTO dbo.countries VALUES ('Austria', 'AT');
INSERT INTO dbo.countries VALUES ('Anguilla', 'AI');
INSERT INTO dbo.countries VALUES ('Antarctica', 'AQ');
INSERT INTO dbo.countries VALUES ('Bahrain', 'BH');
INSERT INTO dbo.countries VALUES ('Barbados', 'BB');
INSERT INTO dbo.countries VALUES ('Botswana', 'BW');
INSERT INTO dbo.countries VALUES ('Bermuda', 'BM');
INSERT INTO dbo.countries VALUES ('Belgium', 'BE');
INSERT INTO dbo.countries VALUES ('Bahamas', 'BS');
INSERT INTO dbo.countries VALUES ('Bangladesh', 'BD');
INSERT INTO dbo.countries VALUES ('Belize', 'BZ');
INSERT INTO dbo.countries VALUES ('Bosnia and Herzegovina', 'BA');
INSERT INTO dbo.countries VALUES ('Bolivia', 'BO');
INSERT INTO dbo.countries VALUES ('Myanmar', 'MM');
INSERT INTO dbo.countries VALUES ('Benin', 'BJ');
INSERT INTO dbo.countries VALUES ('Belarus', 'BY');
INSERT INTO dbo.countries VALUES ('Solomon Islands', 'SB');
INSERT INTO dbo.countries VALUES ('Navassa Island', '\N');
INSERT INTO dbo.countries VALUES ('Brazil', 'BR');
INSERT INTO dbo.countries VALUES ('India', 'IN');
INSERT INTO dbo.countries VALUES ('Bhutan', 'BT');
INSERT INTO dbo.countries VALUES ('Bulgaria', 'BG');
INSERT INTO dbo.countries VALUES ('Bouvet Island', 'BV');
INSERT INTO dbo.countries VALUES ('Brunei Darussalam', 'BN');
INSERT INTO dbo.countries VALUES ('Burundi', 'BI');
INSERT INTO dbo.countries VALUES ('Canada', 'CA');
INSERT INTO dbo.countries VALUES ('Cambodia', 'KH');
INSERT INTO dbo.countries VALUES ('Chad', 'TD');
INSERT INTO dbo.countries VALUES ('Sri Lanka', 'LK');
INSERT INTO dbo.countries VALUES ('DR Congo', 'CD');
INSERT INTO dbo.countries VALUES ('Congo Republic', 'CG');
INSERT INTO dbo.countries VALUES ('China', 'CN');
INSERT INTO dbo.countries VALUES ('Chile', 'CL');
INSERT INTO dbo.countries VALUES ('Cayman Islands', 'KY');
INSERT INTO dbo.countries VALUES ('Cocos (Keeling) Islands', 'CC');
INSERT INTO dbo.countries VALUES ('Cameroon', 'CM');
INSERT INTO dbo.countries VALUES ('Comoros', 'KM');
INSERT INTO dbo.countries VALUES ('Colombia', 'CO');
INSERT INTO dbo.countries VALUES ('Northern Mariana Islands', 'MP');
INSERT INTO dbo.countries VALUES ('Coral Sea Islands', '\N');
INSERT INTO dbo.countries VALUES ('Costa Rica', 'CR');
INSERT INTO dbo.countries VALUES ('Central African Republic', 'CF');
INSERT INTO dbo.countries VALUES ('Cuba', 'CU');
INSERT INTO dbo.countries VALUES ('Cabo Verde', 'CV');
INSERT INTO dbo.countries VALUES ('Cook Islands', 'CK');
INSERT INTO dbo.countries VALUES ('Cyprus', 'CY');
INSERT INTO dbo.countries VALUES ('Denmark', 'DK');
INSERT INTO dbo.countries VALUES ('Djibouti', 'DJ');
INSERT INTO dbo.countries VALUES ('Dominica', 'DM');
INSERT INTO dbo.countries VALUES ('Jarvis Island', '\N');
INSERT INTO dbo.countries VALUES ('Dominican Republic', 'DO');
INSERT INTO dbo.countries VALUES ('Ecuador', 'EC');
INSERT INTO dbo.countries VALUES ('Egypt', 'EG');
INSERT INTO dbo.countries VALUES ('Ireland', 'IE');
INSERT INTO dbo.countries VALUES ('Equatorial Guinea', 'GQ');
INSERT INTO dbo.countries VALUES ('Estonia', 'EE');
INSERT INTO dbo.countries VALUES ('Eritrea', 'ER');
INSERT INTO dbo.countries VALUES ('El Salvador', 'SV');
INSERT INTO dbo.countries VALUES ('Ethiopia', 'ET');
INSERT INTO dbo.countries VALUES ('Europa Island', '\N');
INSERT INTO dbo.countries VALUES ('Czech Republic', 'CZ');
INSERT INTO dbo.countries VALUES ('French Guiana', 'GF');
INSERT INTO dbo.countries VALUES ('Finland', 'FI');
INSERT INTO dbo.countries VALUES ('Fiji', 'FJ');
INSERT INTO dbo.countries VALUES ('Falkland Islands', 'FK');
INSERT INTO dbo.countries VALUES ('Micronesia, Fed. Sts.', 'FM');
INSERT INTO dbo.countries VALUES ('Faeroe Islands', 'FO');
INSERT INTO dbo.countries VALUES ('French Polynesia', 'PF');
INSERT INTO dbo.countries VALUES ('Baker Island', '\N');
INSERT INTO dbo.countries VALUES ('France', 'FR');
INSERT INTO dbo.countries VALUES ('French Southern Territories', 'TF');
INSERT INTO dbo.countries VALUES ('Gambia', 'GM');
INSERT INTO dbo.countries VALUES ('Gabon', 'GA');
INSERT INTO dbo.countries VALUES ('Georgia', 'GE');
INSERT INTO dbo.countries VALUES ('Ghana', 'GH');
INSERT INTO dbo.countries VALUES ('Gibraltar', 'GI');
INSERT INTO dbo.countries VALUES ('Grenada', 'GD');
INSERT INTO dbo.countries VALUES ('Guernsey', 'GG');
INSERT INTO dbo.countries VALUES ('Greenland', 'GL');
INSERT INTO dbo.countries VALUES ('Germany', 'DE');
INSERT INTO dbo.countries VALUES ('Glorioso Islands', '\N');
INSERT INTO dbo.countries VALUES ('Guadeloupe', 'GP');
INSERT INTO dbo.countries VALUES ('Guam', 'GU');
INSERT INTO dbo.countries VALUES ('Greece', 'GR');
INSERT INTO dbo.countries VALUES ('Guatemala', 'GT');
INSERT INTO dbo.countries VALUES ('Guinea', 'GN');
INSERT INTO dbo.countries VALUES ('Guyana', 'GY');
INSERT INTO dbo.countries VALUES ('Haiti', 'HT');
INSERT INTO dbo.countries VALUES ('Hong Kong', 'HK');
INSERT INTO dbo.countries VALUES ('Heard and McDonald Islands', 'HM');
INSERT INTO dbo.countries VALUES ('Honduras', 'HN');
INSERT INTO dbo.countries VALUES ('Howland Island', '\N');
INSERT INTO dbo.countries VALUES ('Croatia', 'HR');
INSERT INTO dbo.countries VALUES ('Hungary', 'HU');
INSERT INTO dbo.countries VALUES ('Iceland', 'IS');
INSERT INTO dbo.countries VALUES ('Indonesia', 'ID');
INSERT INTO dbo.countries VALUES ('Isle of Man', 'IM');
INSERT INTO dbo.countries VALUES ('British Indian Ocean Territory', 'IO');
INSERT INTO dbo.countries VALUES ('Clipperton Island', '\N');
INSERT INTO dbo.countries VALUES ('Iran', 'IR');
INSERT INTO dbo.countries VALUES ('Israel', 'IL');
INSERT INTO dbo.countries VALUES ('Italy', 'IT');
INSERT INTO dbo.countries VALUES ('Cote d''Ivoire', 'CI');
INSERT INTO dbo.countries VALUES ('Iraq', 'IQ');
INSERT INTO dbo.countries VALUES ('Japan', 'JP');
INSERT INTO dbo.countries VALUES ('Jersey', 'JE');
INSERT INTO dbo.countries VALUES ('Jamaica', 'JM');
INSERT INTO dbo.countries VALUES ('Jan Mayen', '\N');
INSERT INTO dbo.countries VALUES ('Jordan', 'JO');
INSERT INTO dbo.countries VALUES ('Johnston Atoll', '\N');
INSERT INTO dbo.countries VALUES ('Juan de Nova Island', '\N');
INSERT INTO dbo.countries VALUES ('Kenya', 'KE');
INSERT INTO dbo.countries VALUES ('Kyrgyz Republic', 'KG');
INSERT INTO dbo.countries VALUES ('North Korea', 'KP');
INSERT INTO dbo.countries VALUES ('Kingman Reef', '\N');
INSERT INTO dbo.countries VALUES ('Kiribati', 'KI');
INSERT INTO dbo.countries VALUES ('South Korea', 'KR');
INSERT INTO dbo.countries VALUES ('Christmas Island', 'CX');
INSERT INTO dbo.countries VALUES ('Kuwait', 'KW');
INSERT INTO dbo.countries VALUES ('Kazakhstan', 'KZ');
INSERT INTO dbo.countries VALUES ('Laos', 'LA');
INSERT INTO dbo.countries VALUES ('Lebanon', 'LB');
INSERT INTO dbo.countries VALUES ('Latvia', 'LV');
INSERT INTO dbo.countries VALUES ('Lithuania', 'LT');
INSERT INTO dbo.countries VALUES ('Liberia', 'LR');
INSERT INTO dbo.countries VALUES ('Slovakia', 'SK');
INSERT INTO dbo.countries VALUES ('Palmyra Atoll', '\N');
INSERT INTO dbo.countries VALUES ('Lesotho', 'LS');
INSERT INTO dbo.countries VALUES ('Luxembourg', 'LU');
INSERT INTO dbo.countries VALUES ('Libya', 'LY');
INSERT INTO dbo.countries VALUES ('Madagascar', 'MG');
INSERT INTO dbo.countries VALUES ('Martinique', 'MQ');
INSERT INTO dbo.countries VALUES ('Macao', 'MO');
INSERT INTO dbo.countries VALUES ('Moldova', 'MD');
INSERT INTO dbo.countries VALUES ('Mayotte', 'YT');
INSERT INTO dbo.countries VALUES ('Mongolia', 'MN');
INSERT INTO dbo.countries VALUES ('Montserrat', 'MS');
INSERT INTO dbo.countries VALUES ('Malawi', 'MW');
INSERT INTO dbo.countries VALUES ('Montenegro', 'ME');
INSERT INTO dbo.countries VALUES ('Macedonia', 'MK');
INSERT INTO dbo.countries VALUES ('Mali', 'ML');
INSERT INTO dbo.countries VALUES ('Monaco', 'MC');
INSERT INTO dbo.countries VALUES ('Morocco', 'MA');
INSERT INTO dbo.countries VALUES ('Mauritius', 'MU');
INSERT INTO dbo.countries VALUES ('Midway Islands', '\N');
INSERT INTO dbo.countries VALUES ('Mauritania', 'MR');
INSERT INTO dbo.countries VALUES ('Malta', 'MT');
INSERT INTO dbo.countries VALUES ('Oman', 'OM');
INSERT INTO dbo.countries VALUES ('Maldives', 'MV');
INSERT INTO dbo.countries VALUES ('Mexico', 'MX');
INSERT INTO dbo.countries VALUES ('Malaysia', 'MY');
INSERT INTO dbo.countries VALUES ('Mozambique', 'MZ');
INSERT INTO dbo.countries VALUES ('New Caledonia', 'NC');
INSERT INTO dbo.countries VALUES ('Niue', 'NU');
INSERT INTO dbo.countries VALUES ('Norfolk Island', 'NF');
INSERT INTO dbo.countries VALUES ('Niger', 'NE');
INSERT INTO dbo.countries VALUES ('Vanuatu', 'VU');
INSERT INTO dbo.countries VALUES ('Nigeria', 'NG');
INSERT INTO dbo.countries VALUES ('Netherlands', 'NL');
INSERT INTO dbo.countries VALUES ('Norway', 'NO');
INSERT INTO dbo.countries VALUES ('Nepal', 'NP');
INSERT INTO dbo.countries VALUES ('Nauru', 'NR');
INSERT INTO dbo.countries VALUES ('Suriname', 'SR');
INSERT INTO dbo.countries VALUES ('Netherlands Antilles', 'AN');
INSERT INTO dbo.countries VALUES ('Nicaragua', 'NI');
INSERT INTO dbo.countries VALUES ('New Zealand', 'NZ');
INSERT INTO dbo.countries VALUES ('Paraguay', 'PY');
INSERT INTO dbo.countries VALUES ('Pitcairn', 'PN');
INSERT INTO dbo.countries VALUES ('Peru', 'PE');
INSERT INTO dbo.countries VALUES ('Paracel Islands', '\N');
INSERT INTO dbo.countries VALUES ('Spratly Islands', '\N');
INSERT INTO dbo.countries VALUES ('Pakistan', 'PK');
INSERT INTO dbo.countries VALUES ('Poland', 'PL');
INSERT INTO dbo.countries VALUES ('Panama', 'PA');
INSERT INTO dbo.countries VALUES ('Portugal', 'PT');
INSERT INTO dbo.countries VALUES ('Papua New Guinea', 'PG');
INSERT INTO dbo.countries VALUES ('Palau', 'PW');
INSERT INTO dbo.countries VALUES ('Guinea-Bissau', 'GW');
INSERT INTO dbo.countries VALUES ('Qatar', 'QA');
INSERT INTO dbo.countries VALUES ('Serbia', 'RS');
INSERT INTO dbo.countries VALUES ('Reunion', 'RE');
INSERT INTO dbo.countries VALUES ('Marshall Islands', 'MH');
INSERT INTO dbo.countries VALUES ('Romania', 'RO');
INSERT INTO dbo.countries VALUES ('Philippines', 'PH');
INSERT INTO dbo.countries VALUES ('Puerto Rico', 'PR');
INSERT INTO dbo.countries VALUES ('Russia', 'RU');
INSERT INTO dbo.countries VALUES ('Rwanda', 'RW');
INSERT INTO dbo.countries VALUES ('Saudi Arabia', 'SA');
INSERT INTO dbo.countries VALUES ('St. Pierre and Miquelon', 'PM');
INSERT INTO dbo.countries VALUES ('St. Kitts and Nevis', 'KN');
INSERT INTO dbo.countries VALUES ('Seychelles', 'SC');
INSERT INTO dbo.countries VALUES ('South Africa', 'ZA');
INSERT INTO dbo.countries VALUES ('Senegal', 'SN');
INSERT INTO dbo.countries VALUES ('St. Helena', 'SH');
INSERT INTO dbo.countries VALUES ('Slovenia', 'SI');
INSERT INTO dbo.countries VALUES ('Sierra Leone', 'SL');
INSERT INTO dbo.countries VALUES ('Singapore', 'SG');
INSERT INTO dbo.countries VALUES ('Somalia', 'SO');
INSERT INTO dbo.countries VALUES ('Spain', 'ES');
INSERT INTO dbo.countries VALUES ('South Sudan', 'SS');
INSERT INTO dbo.countries VALUES ('St. Lucia', 'LC');
INSERT INTO dbo.countries VALUES ('Sudan', 'SD');
INSERT INTO dbo.countries VALUES ('Svalbard and Jan Mayen Islands', 'SJ');
INSERT INTO dbo.countries VALUES ('Sweden', 'SE');
INSERT INTO dbo.countries VALUES ('South Georgia and South Sandwich Is.', 'GS');
INSERT INTO dbo.countries VALUES ('Syria', 'SY');
INSERT INTO dbo.countries VALUES ('Switzerland', 'CH');
INSERT INTO dbo.countries VALUES ('Trinidad and Tobago', 'TT');
INSERT INTO dbo.countries VALUES ('Tromelin Island', '\N');
INSERT INTO dbo.countries VALUES ('Thailand', 'TH');
INSERT INTO dbo.countries VALUES ('Tajikistan', 'TJ');
INSERT INTO dbo.countries VALUES ('Turks and Caicos Islands', 'TC');
INSERT INTO dbo.countries VALUES ('Tokelau', 'TK');
INSERT INTO dbo.countries VALUES ('Tonga', 'TO');
INSERT INTO dbo.countries VALUES ('Togo', 'TG');
INSERT INTO dbo.countries VALUES ('Sao Tome and Principe', 'ST');
INSERT INTO dbo.countries VALUES ('Tunisia', 'TN');
INSERT INTO dbo.countries VALUES ('Timor-Leste', 'TL');
INSERT INTO dbo.countries VALUES ('Turkey', 'TR');
INSERT INTO dbo.countries VALUES ('Tuvalu', 'TV');
INSERT INTO dbo.countries VALUES ('Taiwan', 'TW');
INSERT INTO dbo.countries VALUES ('Turkmenistan', 'TM');
INSERT INTO dbo.countries VALUES ('Tanzania', 'TZ');
INSERT INTO dbo.countries VALUES ('Uganda', 'UG');
INSERT INTO dbo.countries VALUES ('United Kingdom', 'GB');
INSERT INTO dbo.countries VALUES ('Ukraine', 'UA');
INSERT INTO dbo.countries VALUES ('United States', 'US');
INSERT INTO dbo.countries VALUES ('Burkina Faso', 'BF');
INSERT INTO dbo.countries VALUES ('Uruguay', 'UY');
INSERT INTO dbo.countries VALUES ('Uzbekistan', 'UZ');
INSERT INTO dbo.countries VALUES ('St. Vincent and the Grenadines', 'VC');
INSERT INTO dbo.countries VALUES ('Venezuela', 'VE');
INSERT INTO dbo.countries VALUES ('British Virgin Islands', 'VG');
INSERT INTO dbo.countries VALUES ('Vietnam', 'VN');
INSERT INTO dbo.countries VALUES ('United States Virgin Islands', 'VI');
INSERT INTO dbo.countries VALUES ('Namibia', 'NA');
INSERT INTO dbo.countries VALUES ('Palestine', 'PS');
INSERT INTO dbo.countries VALUES ('Wallis and Futuna Islands', 'WF');
INSERT INTO dbo.countries VALUES ('Western Sahara', 'EH');
INSERT INTO dbo.countries VALUES ('Wake Island', '\N');
INSERT INTO dbo.countries VALUES ('Samoa', 'WS');
INSERT INTO dbo.countries VALUES ('Eswatini', 'SZ');
INSERT INTO dbo.countries VALUES ('Yemen', 'YE');
INSERT INTO dbo.countries VALUES ('Zambia', 'ZM');
INSERT INTO dbo.countries VALUES ('Zimbabwe', 'ZW');
