services:
  db:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/1-db-init.sql:ro
      - ./countries.sql:/docker-entrypoint-initdb.d/2-countries.sql:ro
      - ./airlines.sql:/docker-entrypoint-initdb.d/3-airlines.sql:ro
